name: MelosPresentation
packages:
  - packages/**
  - apps/**

command:
  version:
    # Only allow versioning to happen on main branch.
    branch: main
    # Generates a link to a prefilled GitHub release creation page.
    releaseUrl: true

scripts:
format:
  run: melos exec dart format • -fix
  description: Run 'dart format' for all packages.
